#!/usr/bin/env node
/**
 * Phase 14 helper: pushes N renders through the queue and reports where the
 * time goes (queue wait vs. Chromium) so concurrency changes can be judged on
 * measurements rather than vibes.
 *
 * Usage:
 *   node scripts/loadtest.mjs --count 25 --concurrency 5 \
 *     --url http://localhost:8080 --key pdf_sk_xxx --html scripts/sample-certificate.html
 */
import fs from 'node:fs/promises';

const args = new Map();
for (let i = 2; i < process.argv.length; i += 2) {
  const flag = process.argv[i];
  if (!flag?.startsWith('--')) continue;
  args.set(flag.slice(2), process.argv[i + 1]);
}

const baseUrl = (args.get('url') ?? process.env.PDF_URL ?? 'http://localhost:8080').replace(/\/+$/, '');
const apiKey = args.get('key') ?? process.env.PDF_API_KEY;
const count = Number(args.get('count') ?? 10);
const concurrency = Number(args.get('concurrency') ?? 5);
const htmlPath = args.get('html');
const pollMs = Number(args.get('poll') ?? 250);
const timeoutMs = Number(args.get('timeout') ?? 120_000);

if (!apiKey) {
  console.error('Missing API key: pass --key or set PDF_API_KEY');
  process.exit(1);
}

const html = htmlPath
  ? await fs.readFile(htmlPath, 'utf8')
  : '<html><body><h1>Load test</h1><p>Generated by loadtest.mjs</p></body></html>';

const headers = {
  authorization: `Bearer ${apiKey}`,
  'content-type': 'application/json',
};

async function runOne(index) {
  const startedAt = Date.now();
  const enqueue = await fetch(`${baseUrl}/v1/pdf`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ html, filename: `loadtest-${index}.pdf` }),
  });
  const enqueuedMs = Date.now() - startedAt;

  if (enqueue.status !== 202 && enqueue.status !== 200) {
    return { ok: false, stage: 'enqueue', status: enqueue.status, body: await enqueue.text() };
  }
  const { id } = await enqueue.json();

  for (;;) {
    if (Date.now() - startedAt > timeoutMs) {
      return { ok: false, stage: 'timeout', id };
    }
    await new Promise((resolve) => setTimeout(resolve, pollMs));
    const statusResponse = await fetch(`${baseUrl}/v1/jobs/${id}`, {
      headers: { authorization: headers.authorization },
    });
    if (!statusResponse.ok) {
      return { ok: false, stage: 'status', status: statusResponse.status, id };
    }
    const job = await statusResponse.json();
    if (job.status === 'completed') {
      return {
        ok: true,
        id,
        enqueuedMs,
        totalMs: Date.now() - startedAt,
        renderMs: job.result?.render_ms ?? 0,
        workerMs: job.result?.total_ms ?? 0,
        bytes: job.result?.bytes ?? 0,
      };
    }
    if (job.status === 'failed') {
      return { ok: false, stage: 'render', id, error: job.error };
    }
  }
}

function percentile(values, p) {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  const index = Math.min(sorted.length - 1, Math.floor((p / 100) * sorted.length));
  return sorted[index];
}

console.log(`Load test: ${count} jobs, ${concurrency} concurrent, html ${html.length} bytes`);
const wallStart = Date.now();
const results = [];
let next = 0;

await Promise.all(
  Array.from({ length: Math.min(concurrency, count) }, async () => {
    while (next < count) {
      const index = next++;
      results.push(await runOne(index));
    }
  }),
);

const wallMs = Date.now() - wallStart;
const ok = results.filter((result) => result.ok);
const failed = results.filter((result) => !result.ok);
const totals = ok.map((result) => result.totalMs);
const renders = ok.map((result) => result.renderMs);
const queueWaits = ok.map((result) => Math.max(0, result.totalMs - result.workerMs));

console.log('');
console.log(`completed        ${ok.length}/${count}`);
console.log(`failed           ${failed.length}`);
console.log(`wall clock       ${wallMs} ms`);
console.log(`throughput       ${(ok.length / (wallMs / 1000)).toFixed(2)} pdf/s`);
console.log('');
console.log('end-to-end       p50 %d ms  p95 %d ms  max %d ms', percentile(totals, 50), percentile(totals, 95), percentile(totals, 100));
console.log('gotenberg render p50 %d ms  p95 %d ms  max %d ms', percentile(renders, 50), percentile(renders, 95), percentile(renders, 100));
console.log('queue wait       p50 %d ms  p95 %d ms  max %d ms', percentile(queueWaits, 50), percentile(queueWaits, 95), percentile(queueWaits, 100));
if (ok.length > 0) {
  const avgBytes = Math.round(ok.reduce((sum, result) => sum + result.bytes, 0) / ok.length);
  console.log(`average pdf      ${avgBytes} bytes`);
}
for (const failure of failed.slice(0, 5)) {
  console.log('failure:', JSON.stringify(failure));
}
